### ISSUE TITLE
The forum links in OR and Direct should take the user to the vanilla challenge forum

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#137]
The forum links in OR and Direct should take the user to the vanilla challenge forum

**Comment by jmgasper** [comment]
@rootelement - Not sure how you want to tackle this one.

**Comment by rootelement** [comment]
Nope. OR and Direct will still point to Jive. Jive will be shut down at some point when we can get everyone using Work Manager. Only challenges created out of Work Manager will create forums, so that's the only spot that needs to work with Vanilla. 

We will be shutting off features in Direct/OR as they become unnecessary.
