### ISSUE TITLE
Reviewer role has the privilege similar to Copilot

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/forums#140]
Description:
Reviewer role has the privilege similar to Copilot.

Expected Result:

Reviewer should not be able to upload files and Add category.

screenshot:

![image](https://user-images.githubusercontent.com/55895538/98518565-e7001f00-22b2-11eb-9665-78e02041cafa.png)

![image](https://user-images.githubusercontent.com/55895538/98518332-94befe00-22b2-11eb-916e-aef5bea4807d.png)

**Comment by jmgasper** [comment]
@sandhiyakavi - It's because TcConnCopilot is a copilot.  *All* copilots can attach files, regardless of their role in *other* challenges.

@rootelement - Do we need to restrict this per-challenge?  ☝️ 

Right now we configure permissions based on JWT roles, not roles from the resources API per-challenge.
