### ISSUE TITLE
Research scalability

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/forums#4]
Are there other options for database? AWS Aurora? Dynamo?
Can you do two app servers behind a load balancer easily?
Caching (memcached?, varnish?, redis?)

**Comment by jmgasper** [comment]
@rootelement - I think that Aurora should work fine since it's MySQL compatible.

https://aws.amazon.com/rds/aurora/mysql-features/

In terms of load balancing, everything is hosted in Apache, using PHP, which is a pretty standard deploy.  I would assume that setting up something robust, with load balancing, should be relatively straightforward.  That being said, it does also support both nginx and IIS, although IIS isn't "officially" supported:

https://docs.vanillaforums.com/developer/backend/

From the same link above:  `Vanilla has support for both Memcache and Memcached, but we strongly recommend Memcached if you have an option.`

**Comment by rootelement** [comment]
Ok, so we'll go with Aurora and Memcached
