### ISSUE TITLE
Admins still black in production

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#466]
@atelomycterus - After the deploy, we still have a couple admins that are showing as black handles instead of orange, even though they have "Connect Manager" roles.  It looks like that `IsAdmin` flag may be cached in Vanilla - do we need to do anything there to refresh the flag to show those properly as orange?

**Comment by atelomycterus** [comment]
@jmgasper Please apply PR-https://github.com/topcoder-platform/forums-plugins/pull/66/. In https://github.com/topcoder-platform/forums/issues/451 I tested mentions, but  I did not notice that it didn't not work in another case (user creates a comment/discussion). Sorry about that. Fixed. 

I see your commit (https://github.com/topcoder-platform/forums-plugins/commit/72470e8e7801fa68924c99027d972b3405a8a995)  in master branch. There were no typos here,  'connect manager' should be used because  
role names  are converted to lowercase two lines above.  Topcoder API returns different roles 'Administrator', 'Admin', 'administrator', 'admin'. So we look at the intersection of roles in lowercase.

### Testing
- Topcoder user is mentioned  in discussion/comment but he/she hasn't registered in Vanilla
- Topcoder user is mentioned  in discussion/comment. he/she has registered in Vanilla. 
- Topcoder user creates a comment/discussion. 

From local env:
![image](https://user-images.githubusercontent.com/10196632/111318886-845ecb80-8676-11eb-8fe0-d0648c22187e.png)
![image](https://user-images.githubusercontent.com/10196632/111318929-8d4f9d00-8676-11eb-875a-8749b85a2ef9.png)

TODO: After deploying PR, I'll verify https://vanilla.topcoder-dev.com/discussion/4159/test-connect-manager-created-by-tcconmanager - should be displayed in  orange.

**Comment by jmgasper** [comment]
> I see your commit (topcoder-platform/forums-plugins@72470e8) in master branch. There were no typos here, 'connect manager' should be used because
> role names are converted to lowercase two lines above. Topcoder API returns different roles 'Administrator', 'Admin', 'administrator', 'admin'. So we look at the intersection of roles in lowercase.

Yeah, that was just me trying something.  Obviously wrong on my part and it was backed out :)

**Comment by sdgun** [comment]
Verified https://vanilla.topcoder-dev.com/discussion/4159/test-connect-manager-created-by-tcconmanager in Dev and the handle is displayed in orange

![image](https://user-images.githubusercontent.com/4592712/111412735-00065a00-8703-11eb-9822-883ed95db05a.png)

**Comment by sdgun** [comment]
Verified in production, this issue is fixed.

![image](https://user-images.githubusercontent.com/4592712/111419699-eae3f800-870f-11eb-8a38-863107e3b58c.png)

![image](https://user-images.githubusercontent.com/4592712/111419738-fd5e3180-870f-11eb-8136-965560ab9869.png)

**Comment by lakshmiathreya** [comment]
@sdgun this prompted a hotfix - which means it should have the highest priority label P0... cc @SathyaJayabal
