### ISSUE TITLE
Up votes/down votes requests are taking a long time and throwing 502/503 errors

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#569]
**Steps**
Do up vote and down votes on comments/discussions

These calls mostly take more than 10 seconds and observed going up to like 36 seconds to complete the request and throwing 502/503 errors very frequently

[Screencast 2021-04-13.zip](https://github.com/topcoder-platform/forums/files/6301094/Screencast.2021-04-13.zip)

**Comment by atelomycterus** [comment]
@sdgun @jmgasper  502/503 errors happened because there have been about 23,6K requests on DEV. 
I see a bunch of suspicious requests in Tideways. It looks like someone is probing Vanilla DEV to see if we are vulnerable:
![image](https://user-images.githubusercontent.com/10196632/114499960-d2440080-9c2f-11eb-9c2b-e35182580f88.png)

![image](https://user-images.githubusercontent.com/10196632/114500302-6910bd00-9c30-11eb-958d-7c8f729be39a.png)

![image](https://user-images.githubusercontent.com/10196632/114500242-50080c00-9c30-11eb-9900-b18806f8cf47.png)

**Comment by jmgasper** [comment]
@atelomycterus - Ok, thanks.  We'll keep an eye on it to see if it clears.

**Comment by atelomycterus** [comment]
@jmgasper Now Vanilla DEV works as expected. There were suspicious requests that are trying to execute not only Get methods. I think we need to hide, for example, an unused Vanilla REST API, especially one that is not used and can update data.

I'm checking Vanilla logs because Tideways sample rate is 25%.

**Comment by atelomycterus** [comment]
@jmgasper They were trying to see what system we are running, likely to help choose the next attacks.
13k out of 23.6K requests returned 404 (Not found). There have been various attempts here like sql injection, command injection, php / js code execution, etc.
