### ISSUE TITLE
The up/down vote buttons are clickable in guest mode 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#578]
**Steps**
Open https://vanilla.topcoder-dev.com
without logging in go to any public discussion
click on up/down vote icons

**Actual behavior**
There is nothing happening in the UI but a post call is sent

![image](https://user-images.githubusercontent.com/4592712/115059868-c80e5480-9f04-11eb-9091-38a7b333fc8f.png)

**Comment by atelomycterus** [comment]
@jmgasper From MarvelApp it is not clear what behavior is expected for guests. For example, for guests, instead of a comment form, we show `Sign In or Register to comment.`  If  a guest clicks on the Vote up/down button, should  we redirect to 'Sign URL' or should the voting control be hidden and the `Sign In or Register to vote up/down` message is displayed?

Comment forms are hidden for guests:
![image](https://user-images.githubusercontent.com/10196632/115060824-fe41d900-9ef0-11eb-9010-9566dfabface.png)

**Comment by jmgasper** [comment]
@atelomycterus - Can we just ignore a click on the up / down control for now if the user isn't logged in?

**Comment by atelomycterus** [comment]
@jmgasper Sure, please apply PR-https://github.com/topcoder-platform/forums-plugins/pull/91. Thanks!

**Comment by sdgun** [comment]
Verified in Dev, the icons are not clickable for guests.

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/115131891-2dec0080-a019-11eb-8139-101767c4b3e2.png)
